[appenders.starn]
kind = "rolling_file"
path = "log/starn.log"

[appenders.starn.policy]
[appenders.starn.policy.trigger]
kind = "size"
limit = "10 mb"
[appenders.starn.policy.roller]
kind = "fixed_window"
pattern = '{0}/starn.log.{{}}'
base = 1
count = 10

[appenders.starn.encoder]
pattern = "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"

[[appenders.starn.filters]]
kind = "threshold"
level = "info"

[appenders.server]
kind = "rolling_file"
path = "log/server.log"

[appenders.server.policy]
[appenders.server.policy.trigger]
kind = "size"
limit = "10 mb"
[appenders.server.policy.roller]
kind = "fixed_window"
pattern = '{0}/server.log.{{}}'
base = 1
count = 10

[appenders.server.encoder]
pattern = "{m}{n}"

[[appenders.starn.filters]]
kind = "threshold"
level = "info"

[appenders.db]
kind = "rolling_file"
path = "log/db.log"

[appenders.db.policy]
[appenders.db.policy.trigger]
kind = "size"
limit = "10 mb"
[appenders.db.policy.roller]
kind = "fixed_window"
pattern = '{0}/db.log.{{}}'
base = 1
count = 10

[appenders.db.encoder]
pattern = "{d(%+)(utc)} [{f}:{L}] {h({l})} {M}:{m}{n}"

[[appenders.db.filters]]
kind = "threshold"
level = "info"

[[appenders.server.filters]]
kind = "threshold"
level = "info"

[root]
level = "warn"
appenders = [ "starn" ]

[loggers.server]
level = "info"
appenders = ["server"]
additive = false

[loggers.starn]
level = "info"
appenders = ["starn"]
additive = false

[loggers.db]
level = "info"
appenders = ["db"]
additive = false
