[default]
address = "127.0.0.1"
port = 8000
log_level = "off"

[default.databases.starn]
url = "mongodb://starn:root#starn@mongo:27017/starn?connect=direct"

[release]
address = "0.0.0.0"
port = 8080
log_level = "off"

[release.databases.starn]
url = "mongodb://starn:root#starn@mongo:27017/starn?connect=direct"
