[default]
address = "127.0.0.1"
port = 8000
log_level = "debug"

[default.databases.starn]
url = "mongodb://starn:statics%40web@127.0.0.1:27017/starn"

[release]
address = "0.0.0.0"
port = 8080
log_level = "off"

[release.databases.starn]
url = "mongodb://starn:statics%40web@mongo:27017/starn"
